version: '3'

volumes:
  yogo_local_postgres_data: {}
  yogo_local_postgres_data_backups: {}

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/web/Dockerfile
    image: yogo_local_web
    container_name: yogo_local_web
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local/.web
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: yogo_production_postgres
    container_name: yogo_local_postgres
    volumes:
      - yogo_local_postgres_data:/var/lib/postgresql/data
      - yogo_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

#  docs:
#    image: first_cookiecutter_demo_local_docs
#    container_name: first_cookiecutter_demo_local_docs
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - .envs/.local/.web
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./first_cookiecutter_demo:/app/first_cookiecutter_demo:z
#    ports:
#      - '9000:9000'
#    command: /start-docs

  mailpit:
    image: axllent/mailpit:latest
    container_name: golang_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: yogo_local_redis
