url: http://127.0.0.1:8066
swagger_open: true
dev_fresh: 1
path:
  storage: "/home/peter/testdata/storage/"
  log: ""
  pid: ""
  cache: ""
dev:
  port: 8087
  backend:
    refresh_time: 1
    port: 8072
    monitor_folder: ""
  frontend:
    port: 8071
