postgres:
    hostname: 127.0.0.1
    username: postgres
    password: env(DB_PASSWORD)
    timeout: 1
    readtime: 2.3

default:
    driver: postgres
    hostname: localhost
    database: yogo
    username: root
    password: "123456"
    charset:
    collation:
