conn_max_idle: 10 # 通用配置，连接池最大空闲连接数
conn_max_open: 100 # 通用配置，连接池最大连接数
conn_max_lifetime: 1h # 通用配置，连接数最大生命周期
protocol: tcp # 通用配置，传输协议
loc: Local # 通用配置，时区

default:
    driver: postgres # 连接驱动
    dsn: "host=localhost user=test password=123123 dbname=test port=5432 sslmode=disable TimeZone=Asia/Shanghai" # dsn，如果设置了dsn, 以下的所有设置都不生效
    # host: localhost # ip地址
    # port: 5432 # 端口
    # database: test # 数据库
    # username: 26huitailang # 用户名
    # password: "" # 密码
    # timeout: 10s # 连接超时
    # read_timeout: 2s # 读超时
    # write_timeout: 2s # 写超时
    # parse_time: true # 是否解析时间
    # protocol: tcp # 传输协议
    # loc: Local # 时区
