name: yogo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          cache: true

      - name: Go version
        run: go version

      - name: Build
        env:
          GOPROXY: https://proxy.golang.com.cn,direct
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
